feat(chips): adds blue chip type
HealthCatalyst/Fabric.Cashmere pull request #1411
Opened 2020-10-12 20:01 UTC by andrew-frueh

Hey Joe, I made some style adjustments to your PR.  Based on how it was being used, it made more sense for that notification above the Bit tile to be a chip - but as I made that switch it exposed a few shortcomings of the component.  I added a `tight` param that we have on several other components that removes margin/padding.  And I added a `width` param so the dev can decide whether the chip should take the full width of its space (it's currently set to auto).

I also cleaned up some formatting on your guide. Let me know if you have any concerns.

2020-10-12 20:08 UTC, joeskeen requested changes
Just a couple small changes, for the most part looks awesome!

2020-10-12 20:08 UTC, joeskeen commented on projects/cashmere/src/lib/chip/chip.component.html
> +<div class="hc-chip hc-chip-{{color}}" [ngClass]="{'hc-chip-padding': !tight}" [ngStyle]="{'width': width}">
I would much prefer the following:

```html
<div class="hc-chip hc-chip-{{color}}" [class.hc-chip-padding]="!tight" [style.width]="width">
```

2020-10-12 20:10 UTC, andrew-frueh commented on projects/cashmere/src/lib/chip/chip.component.html
> +<div class="hc-chip hc-chip-{{color}}" [ngClass]="{'hc-chip-padding': !tight}" [ngStyle]="{'width': width}">
Ah, good call - I'll update that.

2020-10-12 21:53 UTC, merged

2020-10-14 17:58 UTC, benjanderson commented
:tada: This PR is included in version 8.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@healthcatalyst/cashmere/v/8.0.0)
- [GitHub release](https://github.com/HealthCatalyst/Fabric.Cashmere/releases/tag/v8.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: