fix(datepicker): fixed the minutes max/min
HealthCatalyst/Fabric.Cashmere pull request #1630
Opened 2021-05-21 22:29 UTC by WistyDagel

closes #1628

2021-05-24 15:49 UTC, corykon approved these changes

2021-05-24 21:21 UTC, andrew-frueh requested changes
One fix here and then good to go

2021-05-24 21:21 UTC, andrew-frueh commented on projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts
> +                curMin = 1;
hey @WistyDagel - this should actually get set to 0 instead of 1 so that 3:59 loops to 3:00 instead of 3:01

2021-05-24 21:37 UTC, andrew-frueh approved these changes

2021-05-24 21:37 UTC, merged

2021-05-25 17:15 UTC, benjanderson commented
:tada: This PR is included in version 10.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@healthcatalyst/cashmere/v/10.5.0)
- [GitHub release](https://github.com/HealthCatalyst/Fabric.Cashmere/releases/tag/v10.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: