docs(react-cashmere): adding link to react-cashmere GH pages
HealthCatalyst/Fabric.Cashmere pull request #1931
Opened 2022-08-24 17:15 UTC by sheaivey

Tweaking the Web Apps dropdown to have `</> Angular Components` and `</> React Components`. The react components links over to `react-cashmere` storybook.

I have also made the `react-cashmere` library public.

2022-08-24 17:22 UTC, andrew-frueh requested changes
Hey Shea, this looks good but lets do `target="_blank"` for the anchor link here (since it opens a separate site)

2022-08-24 17:26 UTC, sheaivey commented
I have made the `target="_blank"` request. 👍

2022-08-24 18:31 UTC, andrew-frueh approved these changes

2022-08-24 18:31 UTC, merged

2022-08-29 16:38 UTC, health-catalyst commented
:tada: This PR is included in version 13.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@healthcatalyst/cashmere/v/13.2.1)
- [GitHub release](https://github.com/HealthCatalyst/Fabric.Cashmere/releases/tag/v13.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: