fix(sidenav): fix dangling character cutoff
HealthCatalyst/Fabric.Cashmere pull request #2246
Opened 2023-10-09 21:37 UTC by bradcypert

set overflow to visible for tab name

re: #2244

2023-10-09 21:59 UTC, bradcypert commented
There's a chance that more work is required here. Upon inspection it seems that there's two style declarations for the same class name, one for the standard scss and one for component specific css. Just wanted to call out that the contents of this style block is not in sync between the two. Maybe that's okay, maybe not but I wanted to mention it :)

2023-10-10 17:57 UTC, corykon requested changes
Thanks for submitting Brady! We want to make sure we handle cases where the tab name is too long by truncating and adding ellipsis. Setting overflow to visible will break this. 

I would recommend setting the overflow back to hidden, and then adding something like this: `line-height: 1.5;`

2023-10-10 21:07 UTC, bradcypert commented
@corykon great call! I've updated the scss to reflect your suggestions

2023-10-10 21:52 UTC, corykon approved these changes

2023-10-10 21:53 UTC, merged

2023-10-16 20:03 UTC, health-catalyst commented
:tada: This PR is included in version 15.3.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@healthcatalyst/cashmere/v/15.3.4)
- [GitHub release](https://github.com/HealthCatalyst/Fabric.Cashmere/releases/tag/v15.3.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: