feat(progress-indicators): progress bar component
HealthCatalyst/Fabric.Cashmere pull request #2300
Opened 2024-05-16 16:07 UTC by andrew-frueh

adds progress bar component to progress indicators module

closes #2295

2024-05-16 16:49 UTC, corykon requested changes
Looks awesome, thanks @andrew-frueh 

Noticed the example doesn't show the progress when set to determinate w/out the progress value displayed.

<img width="1031" alt="image" src="https://github.com/HealthCatalyst/Fabric.Cashmere/assets/12416432/a54eb529-19bd-46ff-a688-37bc440b2293">

2024-05-16 17:19 UTC, andrew-frueh commented
Good catch @corykon - thanks for the quick review.  Should be corrected now.

2024-05-17 17:46 UTC, corykon approved these changes

2024-05-17 17:46 UTC, merged

2024-05-17 18:34 UTC, health-catalyst commented
:tada: This PR is included in version 16.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@healthcatalyst/cashmere/v/16.3.0)
- [GitHub release](https://github.com/HealthCatalyst/Fabric.Cashmere/releases/tag/v16.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: